In [10]:
%%timeit
n = 1000000
sum = 0
for i in range(n):
    sum += i


45.5 ms ± 4.59 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
import numpy as np

In [15]:
%%timeit
n = 1000000
i = np.arange(n)
sum = np.sum(i)

1.68 ms ± 210 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [12]:
45.5/1.29

35.27131782945737

In [16]:
a = [1,2,3,4]
b = [5,6,7,8]
a + b

[1, 2, 3, 4, 5, 6, 7, 8]

In [17]:
a = list('hello')
b = list('world')
a + b

['h', 'e', 'l', 'l', 'o', 'w', 'o', 'r', 'l', 'd']

In [20]:
a = [1,2,3,4]
b = [5,6,7,8]
c = []
for i in range(len(a)):
    c.append(a[i]+b[i])
c

[6, 8, 10, 12]

In [23]:
a = [1,2,3,4]
b = [5,6,7,8]
c = [a[i]+b[i] for i in range(len(a))]
c

[6, 8, 10, 12]

In [24]:
import numpy as np

In [26]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = a + b

In [27]:
np.sin(c)

array([-0.2794155 ,  0.98935825, -0.54402111, -0.53657292])

In [28]:
np.exp(c)

array([   403.42879349,   2980.95798704,  22026.46579481, 162754.791419  ])

In [29]:
np.log(c)

array([1.79175947, 2.07944154, 2.30258509, 2.48490665])

In [30]:
np.cos(c)

array([ 0.96017029, -0.14550003, -0.83907153,  0.84385396])

In [31]:
c**2

array([ 36,  64, 100, 144])

In [32]:
c**0.5

array([2.44948974, 2.82842712, 3.16227766, 3.46410162])

In [36]:
c.dtype

dtype('int32')

In [45]:
a = np.array([1,2,3,4], 'float32')
b = np.array([3.5,4.5,5.5,6.5],'float32')

In [44]:
a.dtype

dtype('float32')

In [40]:
b.dtype

dtype('float64')

In [46]:
c = a + b

In [47]:
c.dtype

dtype('float32')

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
d = np.zeros([3,3])

In [53]:
d.shape

(3, 3)

In [54]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [55]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [58]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [59]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [61]:
np.arange(0,1.1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [73]:
np.random.randn()

0.7864981514073631

In [74]:
data1d = np.array([1, 2, 3])               # 一维数组
data2d = np.array([[1,2], [3,4]])          # 二维数组
mixed_type = np.array([1, "two", 3.0])     # 类型自动提升 → dtype='<U21'


In [78]:
data2d[1,1]

4

In [79]:
c = [[1,2], [3,4]]

In [81]:
c[1][1]

4

In [91]:
# 2. 特殊矩阵生成
zeros_arr = np.zeros((2,3))                # 2行3列浮点零矩阵
ones_int = np.ones(3, dtype=np.int32)   # 含三个1的整型数组
full_arr = np.full((2,2), 9.9)             # 2x2全9.9矩阵

In [95]:
np.full((2,2), 90.0)

array([[90., 90.],
       [90., 90.]])

In [96]:
a = 1+1j

In [97]:
a

(1+1j)

In [105]:
complex_arr = np.array([1, 2], dtype=np.complex128)

In [106]:
complex_arr

array([1.+0.j, 2.+0.j])

In [109]:
-2**31

-2147483648

In [110]:
2**31-1

2147483647

In [111]:
# 调整数组维度
original = np.arange(24)
reshaped = original.reshape(4, 6)  # 4行6列矩阵

# 自动推导维度
auto_shape = np.linspace(0,10,12).reshape(3, -1)  # 3x4矩阵

# 初始化后填充
empty_matrix = np.empty((3,3))    # 分配内存但不初始化
np.copyto(empty_matrix, [[9,8,7],[6,5,4],[3,2,1]])

print("自动推导形状:\n", auto_shape)
print("\n拷贝填充后矩阵:\n", empty_matrix)

自动推导形状:
 [[ 0.          0.90909091  1.81818182  2.72727273]
 [ 3.63636364  4.54545455  5.45454545  6.36363636]
 [ 7.27272727  8.18181818  9.09090909 10.        ]]

拷贝填充后矩阵:
 [[9. 8. 7.]
 [6. 5. 4.]
 [3. 2. 1.]]


In [116]:
# 调整数组维度
original = np.arange(24)
reshaped = original.reshape(4, 6)  # 4行6列矩阵

In [113]:
original

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [119]:
# 自动推导维度
auto_shape = np.linspace(0,10,12).reshape(3, 2, -1)  # 3x4矩阵

In [120]:
auto_shape

array([[[ 0.        ,  0.90909091],
        [ 1.81818182,  2.72727273]],

       [[ 3.63636364,  4.54545455],
        [ 5.45454545,  6.36363636]],

       [[ 7.27272727,  8.18181818],
        [ 9.09090909, 10.        ]]])

In [122]:
import numpy as np

# 创建3x4随机整数数组（0-9）
arr = np.random.randint(0, 10, size=(3,4))
print("原始数组:\n", arr)
print("\n核心属性:")
print("数组维度:", arr.ndim)     # 2
print("形状信息:", arr.shape)    # (3,4)
print("元素总数:", arr.size)     # 12
print("数据类型:", arr.dtype)    # int32
print("单个元素字节:", arr.itemsize)  # 4
print("存储顺序:", arr.flags)     # 展示内存布局信息

原始数组:
 [[2 7 0 3]
 [9 7 0 4]
 [9 8 0 1]]

核心属性:
数组维度: 2
形状信息: (3, 4)
元素总数: 12
数据类型: int32
单个元素字节: 4
存储顺序:   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [123]:
# 基础形状变换
arr1d = np.arange(12)            # [0 1 2 ...11]

# 行列转换
matrix = arr1d.reshape(3,4)       # 转3x4二维数组
tensor = matrix.reshape(2,2,3)    # 转为2x2x3三维数组

# 自动推算维度
auto_shape = arr1d.reshape(3, -1)  # 自动计算第二维为4
print("-1自动推导数组:\n", auto_shape)

# 展平操作对比
print("\n展平方法:")
print("flatten结果:", matrix.flatten())  # 使用拷贝（复制数据）
print("ravel结果:", matrix.ravel())      # 视图（原始数据引用）

-1自动推导数组:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

展平方法:
flatten结果: [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel结果: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [124]:
# 一维数组索引
arr = np.arange(10)               # [0 1 2 3 4 5 6 7 8 9]
print("一维示例:")
print("4号元素:", arr[4])         # 4
print("步长切片:", arr[1:7:2])     # [1 3 5]

# 多维数组访问
matrix = np.arange(12).reshape(3,4)
print("\n二维数组:")
print("首行:", matrix[0])         # [0 1 2 3]
print("末列:", matrix[:,-1])      # [3 7 11]
print("区域访问:", matrix[1:, :2]) # [[4,5], [8,9]]

# 布尔索引
filter_arr = matrix[matrix > 7]   # 保留所有大于7的元素
print("\n布尔筛选:\n", filter_arr)  # [ 8  9 10 11]

# 导步索引（视图）
slice_view = matrix[::2, ::2]     # 使用导步生成视图
slice_view[0,0] = 99             # 修改会影响原始数组
print("\n导步切片影响原数组:\n", matrix)

一维示例:
4号元素: 4
步长切片: [1 3 5]

二维数组:
首行: [0 1 2 3]
末列: [ 3  7 11]
区域访问: [[4 5]
 [8 9]]

布尔筛选:
 [ 8  9 10 11]

导步切片影响原数组:
 [[99  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [131]:
matrix = np.arange(12).reshape(3,4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [135]:
filter_arr = matrix[matrix > 5]   # 保留所有大于7的元素
filter_arr

array([ 6,  7,  8,  9, 10, 11])

In [136]:
matrix > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [137]:
slice_view = matrix[::2, ::2]     # 使用导步生成视图

In [138]:
slice_view

array([[ 0,  2],
       [ 8, 10]])

In [142]:
slice_view[1,1] = 99             # 修改会影响原始数组


In [143]:
slice_view

array([[99,  2],
       [ 8, 99]])

In [144]:
matrix

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 99, 11]])

In [145]:
origin = np.array([[1,2],[3,4]])

view_arr = origin[0,:]    # 视图（数据共享）
copy_arr = origin.copy()  # 深拷贝

view_arr[0] = 99          # 修改视图影响原数组
copy_arr[1,1] = 88        # 不影响原数据

print("原始数组:\n", origin)  # [[99 2], [3 4]]
print("副本数组:\n", copy_arr)  # [[1 2], [3 88]]

原始数组:
 [[99  2]
 [ 3  4]]
副本数组:
 [[ 1  2]
 [ 3 88]]


In [146]:
# 复杂数据结构初始化
dtype = [('name', 'U10'), ('score', float)]
ones_struct = np.ones(3, dtype=dtype)  # 结构化数组
print("\n结构化全1数组:", ones_struct)


结构化全1数组: [('1', 1.) ('1', 1.) ('1', 1.)]


In [151]:
ones_struct[0] = ('张三', 59)

In [152]:
ones_struct[1] = ('李四', 58)

In [153]:
ones_struct[2] = ('王五', 57)

In [157]:
ones_struct['score'] = ones_struct['score']**0.5*10

In [158]:
ones_struct

array([('张三', 76.81145748), ('李四', 76.15773106), ('王五', 75.49834435)],
      dtype=[('name', '<U10'), ('score', '<f8')])

In [160]:
# 单位矩阵替代方案
ones_square = np.ones((3,3))  # 3x3全1浮点矩阵
print("标准全1矩阵:\n", ones_square)
# 矩阵运算测试
print("\n矩阵运算:")
print(ones_square * 5 + 2)  # 广播运算

标准全1矩阵:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

矩阵运算:
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [161]:
# 网格坐标生成（结合shape）
x = np.arange(3)
y = np.arange(4)
xx, yy = np.meshgrid(x, y)  # 生成网格坐标矩阵

In [162]:
xx

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [163]:
yy

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [164]:
np.sin(xx) * np.cos(yy)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.        ,  0.45464871,  0.4912955 ],
       [-0.        , -0.35017549, -0.37840125],
       [-0.        , -0.83304996, -0.90019763]])

In [165]:
# 时间序列生成（Pandas扩展更优）
time_steps = np.arange('2023-01', '2023-03', dtype='datetime64[D]')


In [166]:
time_steps

array(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
       '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
       '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
       '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
       '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
       '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
       '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
       '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
       '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
       '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
       '2023-02-10', '2023-02-11', '2023-02-12', '2023-02-13',
       '2023-02-14', '2023-02-15', '2023-02-16', '2023-02-17',
       '2023-02-18', '2023-02-19', '2023-02-20', '2023-02-21',
       '2023-02-22', '2023-02-23', '2023-02-24', '2023-02-25',
       '2023-02-26', '2023-02-27', '2023-02-28'], dtype='datetime64[D]')

In [167]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6]])

# 元素级算术运算
print("加法:\n", arr + 10)       # 所有元素+10
print("\n乘法:\n", arr * 2)      # 所有元素×2
print("\n幂运算:\n", arr ** 2)   # 各元素平方

# 数学函数应用
print("\n自然对数:\n", np.log(arr))
print("\n正弦值:\n", np.sin(arr))

# 矩阵运算
matrix = arr.reshape(2,3)
print("\n矩阵转置:\n", matrix.T)       # 3x2转置矩阵
print("矩阵乘法:\n", np.dot(matrix, matrix.T))  # 2x2矩阵

加法:
 [[11 12 13]
 [14 15 16]]

乘法:
 [[ 2  4  6]
 [ 8 10 12]]

幂运算:
 [[ 1  4  9]
 [16 25 36]]

自然对数:
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]

正弦值:
 [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]

矩阵转置:
 [[1 4]
 [2 5]
 [3 6]]
矩阵乘法:
 [[14 32]
 [32 77]]


In [168]:
# 矩阵运算
matrix = arr.reshape(2,3)
print("\n矩阵转置:\n", matrix.T)       # 3x2转置矩阵
print("矩阵乘法:\n", np.dot(matrix, matrix.T))  # 2x2矩阵


矩阵转置:
 [[1 4]
 [2 5]
 [3 6]]
矩阵乘法:
 [[14 32]
 [32 77]]


In [171]:
matrix @ matrix.T

array([[14, 32],
       [32, 77]])

In [172]:
a = np.array([[0,0], [10,10]])  # shape (2,2)
b = np.array([1,2])             # shape (2,)

# 广播过程：b → [[1,2], [1,2]]
result = a + b  
print("广播加法结果:\n", result)

# 3维广播示例
c = np.arange(6).reshape(3,1,2)  # shape (3,1,2)
d = np.array([10,100])          # shape (2,)
print("\n三维广播运算:\n", c * d)  # 最终形状 (3,1,2)

广播加法结果:
 [[ 1  2]
 [11 12]]

三维广播运算:
 [[[  0 100]]

 [[ 20 300]]

 [[ 40 500]]]


In [173]:
a = np.array([[0,0], [10,10]])  # shape (2,2)
b = np.array([1,2])             # shape (2,)

In [180]:
a = np.array([[0,0], [10,10], [20,20]])  # shape (2,2)


In [181]:
b

array([1, 2])

In [186]:
a * [2,3]

array([[ 0,  0],
       [20, 30],
       [40, 60]])

In [190]:
c = np.arange(24).reshape(-1,2,2)  # shape (3,1,2)
d = np.array([[1,1],[2,2]])          # shape (1,2)
print("\n三维广播运算:\n", c * d)  # 最终形状 (3,1,2)



三维广播运算:
 [[[ 0  1]
  [ 4  6]]

 [[ 4  5]
  [12 14]]

 [[ 8  9]
  [20 22]]

 [[12 13]
  [28 30]]

 [[16 17]
  [36 38]]

 [[20 21]
  [44 46]]]


In [2]:
with open('test.txt', 'w+') as f:
    f.write('hello')

In [ ]:
f = open('test.txt', 'w+')
f.write('hello')
f.close()